apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo-workflows
  namespace: argo
spec:
  entryPoints:
    - websecure
  tls: {}
  routes:
    - kind: Rule
      match: Host(`argo-workflows.k3d.localhost`)
      priority: 10
      services:
        - name: argo-workflows-server
          port: 2746
